args <- commandArgs(TRUE)

family_mean  <- read.table(args[1], header = T, sep="\t", check.names=FALSE, fill=TRUE)
mean_agg =aggregate(. ~ family, data = family_mean, mean)
metag <- subset(mean_agg, select=-c(tax_id,species,genus,order,class,phylum,kingdom,superkingdom))
metag <- subset(metag, select=c(ncol(metag),1:(ncol(metag)-1)))
metag <- subset(metag, select=-c(taxname))
write.table(metag, file="family_taxainfo_mean.txt", sep="\t", row.names = FALSE)

family_uniq <- read.table(args[2], header = T, sep="\t", check.names=FALSE, fill=TRUE)
uniq_agg=aggregate(. ~ family, data=family_uniq, mean)
metag_uniq <- subset(uniq_agg, select=-c(tax_id,species,genus,order,class,phylum,kingdom,superkingdom))
metag_uniq <- subset(metag_uniq, select=c(ncol(metag_uniq),1:(ncol(metag_uniq)-1)))
metag_uniq <- subset(metag_uniq, select=-c(taxname))
write.table(metag_uniq, file="family_taxainfo_unique_sequences.txt", sep="\t", row.names = FALSE)

family_quant <- read.table (args[3], header = T, sep="\t", check.names=FALSE, fill=TRUE)
quant_agg=aggregate(. ~ family, data=family_quant, mean)
metag_quant <- subset(uniq_agg, select=-c(tax_id,species,genus,order,class,phylum,kingdom,superkingdom))
metag_quant <- subset(metag_quant, select=c(ncol(metag_quant),1:(ncol(metag_quant)-1)))
metag_quant <- subset(metag_quant, select=-c(taxname))
write.table(metag_uniq, file="family_taxainfo_quantification_accuracy.txt", sep="\t", row.names = FALSE)
